namespace eCobranca.Enumerator;

public enum EnumTipoNotificacao
{
	CRIAR_CARTEIRA_COBRANCA,
	CARREGAR_CARTEIRA_COBRANCA,
	SALVAR_CARTEIRA_COBRANCA,
	BLOQUEAR_ESCRITA_CARTEIRA_COBRANCA,
	LIBERAR_ESCRITA_CARTEIRA_COBRANCA,
	DADO_CONFIGURACAO_CARTEIRA_ALTERADO,
	CARTEIRA_COBRANCA_CRIADA,
	CARTEIRA_COBRANCA_GRAVADA,
	CARTEIRA_COBRANCA_CARREGADA,
	ATUALIZAR_MENSAGEM_ERRO,
	ATUALIZAR_SEQUENCIA_TRAILLER_CNAB400,
	SET_REFERENCIA_PARAMETROS_DISPONIVEIS,
	GET_NOME_ARQUIVO_REMESSA,
	SET_NOME_ARQUIVO_REMESSA,
	GET_LAYOUT_REMESSA,
	SET_LAYOUT_REMESSA,
	LIBERAR_RECURSOS,
	SET_REFERENCIA_CARTEIRA_COBRANCA,
	SET_GUID,
	CARREGAR_MODELOS_BOLETO,
	INSTANCIAR_CARTEIRA_COBRANCA,
	CARTEIRA_COBRANCA_INSTANCIADA
}
